.github/workflows/rebase.yml

ci(gh-action): add rebase action

---

README.md

add todo to implement `@for` directive support

docs(readme): update readme.md

---

src/main.js

fix: 🐛 preserve original if attempting overwrite with nothing

---

__tests__/cli.test.js
__tests__/fixtures/commented.blade.php
__tests__/fixtures/formatted.commented.blade.php
__tests__/formatter.test.js
package.json
src/formatter.js
src/util.js
yarn.lock

refs #11 
I would like to support `@for` directive to produce more consistent format result.

Support `@for` directive

---

README.md

chore: Remove unnecessary comma in README

---

__tests__/cli.test.js
__tests__/fixtures/blade_comment_in_longline.blade.php
__tests__/fixtures/commented.blade.php
__tests__/fixtures/formatted.blade_comment_in_longline.blade.php
__tests__/fixtures/formatted.commented.blade.php
__tests__/fixtures/formatted.if_nest.blade.php
__tests__/fixtures/formatted_shorttag.blade.php
__tests__/fixtures/if_nest.blade.php
__tests__/formatter.test.js
src/formatter.js
src/util.js

fixes nested if directive problem #117

---

src/cli.js
src/formatter.js

Added a new option in CLI and formatter to wrap attributes.
Additional config options.
Not tested at all - please trest.

Added new option in CLI and formatter

---

__tests__/formatter.test.js
src/util.js

✅ Closes: #14
refs: #14 
Fixes problem that curly braces without content causes exception 
CI

fix: 🐛 allow empty curly braces

---

__tests__/fixtures/formatted_inline_php_tag.blade.php
__tests__/fixtures/inline_php_tag.blade.php
__tests__/formatter.test.js
src/formatter.js
src/util.js

Fixes #129
Reserve php directive in html tag.
- #129

fix: 🐛 reserve php directive in html tag

---

__tests__/formatter.test.js
src/util.js

fix: 🐛 long line with inline directive occurs error

---

.bladeignore
__tests__/cli.test.js
__tests__/fixtures/ignore_target_file.blade.php
package.json
src/main.js
yarn.lock

Close #198 
#198 , #9 
Some situation like email template or blade-formatter error requires ignore specific files.
To achieving this, I added`.bladeignore` file supporting .gitignore syntax to ignore specific files.
end to end test on jest

feat: 🎸 introduce .bladeignore

---

__tests__/cli.test.js
__tests__/fixtures/formatted.raw_php_block.blade.php
__tests__/fixtures/raw_php_block.blade.php
__tests__/formatter.test.js
src/formatter.js

✅ Closes: #200 
Fixes flatten problem on raw `@php` block
- #200

fix: 🐛 format raw php block within @php directive

---

__tests__/cli.test.js
__tests__/fixtures/formatted.blade_comment_in_longline.blade.php
__tests__/fixtures/formatted.commented.blade.php
__tests__/fixtures/formatted.multiline_blade_comment.blade.php
__tests__/fixtures/multiline_blade_comment.blade.php
src/formatter.js
src/util.js

Sometimes error occur on below temaplte
```blade
{{-- 
aaa bbb
--}}
```
```blade
<div>;{{-- aaaa --}}
```
this PR fixes error on above templates

fix: 🐛 store blade comment to keep comment body

---

__tests__/cli.test.js
__tests__/fixtures/formatted.props.blade.php
__tests__/fixtures/props.blade.php
src/formatter.js

- feat: 🎸 support `@props` directive on component
- test: 💍 add test for `@props` directive on component
This PR add support for `@props` directive on component.
- https://github.com/shufo/vscode-blade-formatter/issues/70

support props directive on component

---

README.md

chore: Remove duplicate commas in README

---

__tests__/formatter.test.js
src/indent.js
syntaxes/blade.tmLanguage.json

- Added support for `@cannot`, `@canany` directive
- none
- To cover built-in directives for Laravel
see added tests

feature: support for @cannot, @canany directive

---

__tests__/cli.test.js
__tests__/fixtures/formatted.inline_php_directive.blade.php
__tests__/fixtures/inline_php_directive.blade.php
__tests__/support/util.js
src/formatter.js
src/util.js

✅ Closes: #299
- #299
- #299
- see test

fix: 🐛 inline @php directive gets unexpected indent

---

__tests__/cli.test.js
__tests__/fixtures/formatted.overwrite_tag.blade.php
__tests__/fixtures/overwrite_tag.blade.php
src/indent.js

- feat: 🎸 support `@overwrite` directive
- test: 💍 add test for `@overwrite` directive
Currently `@overwrite` directive is not supported.
- fixes: #327 
To support `@overwrite` directive.
see tests.

feat: 🎸 support `@overwrite` directive

---

__tests__/formatter.test.js
src/formatter.js

the currentIndentLevel went negative when using multiple sections in combination with #319
this fixes #326

fix: prevent indent level going negative

---

__tests__/cli.test.js
__tests__/fixtures/formatted.multiline_class.blade.php
__tests__/fixtures/formatted_shorttag.blade.php
__tests__/fixtures/multiline_class.blade.php
src/formatter.js

- fix: 🐛 prevent unexpected indent for braces in class attribute
- chore: 🤖 follow formatting behaviour change
- test: 💍 add test for blade brace in class attribute
- fixes #333
- see tests

fix: prevent unexpected indent on blade brace in class attribute

---

src/formatter.js

fix preseveClass affecting other attributes

---

README.md

docs: ✏️ update README.md

---

package.json
yarn.lock

Bump prettier/plugin-php dependency

chore(dev-deps): bump prettier/plugin-php to 0.17.6

---

package.json
yarn.lock

chore(dep-deps): bump js-beautify to 0.14.0

---

README.md
__tests__/cli.test.ts
__tests__/fixtures/alpine_attributes.blade.php
__tests__/fixtures/formatted.alpine_attributes.blade.php
package.json
src/formatter.ts

Hello @shufo , this PR adds support for formatting x-data and x-init attributes for those using alpine.
There is more work to be done in order to preserve the attribute offset.

feat: x-data and x-init alpine attribute support

---

__tests__/fixtures/alpine_attributes.blade.php
__tests__/fixtures/formatted.alpine_attributes.blade.php
src/formatter.ts

fix: 🐛 handle `@js` and `@entangle` for x-data and x-init

---

__tests__/formatter.test.ts
src/formatter.ts

✅ Closes: #569
This PR fixes #569.
- #569
It should not raise an error if dollar signs are used with nested directives.
see tests

fix: 🐛 dollar sign with nested directive causes error

---

__tests__/formatter.test.ts
src/formatter.ts
src/indent.ts

- feat: 🎸 support aware directive
- test: 💍 add test for @aware directive
This PR closes #576
- #576
`@aware` directive is currently not supported
see tests

feat: 🎸 support aware directive

---

.github/workflows/node.yml
CHANGELOG.md
README.md
__tests__/cli.test.ts
__tests__/fixtures/formatted.blade_comment_in_longline.blade.php
__tests__/fixtures/formatted.multiline_blade_comment.blade.php
__tests__/fixtures/runtimeConfig/tailwind/.bladeformatterrc.json
__tests__/fixtures/runtimeConfig/tailwind/formatted.index.blade.php
__tests__/fixtures/runtimeConfig/tailwind/index.blade.php
__tests__/fixtures/runtimeConfig/tailwind/tailwind.config.example.js
__tests__/fixtures/tailwind/formatted.index.blade.php
__tests__/fixtures/tailwind/index.blade.php
__tests__/fixtures/tailwind/tailwind.config.example.js
__tests__/fixtures/tailwind/tailwind.config.js
__tests__/fixtures/tailwind/tailwind.config.unresolvable.js
__tests__/formatter.test.ts
codecov.yml
package.json
src/cli.ts
src/formatter.ts
src/main.ts
src/runtimeConfig.ts
yarn.lock

Ignore formatting of multi-line blade comments
[https://github.com/shufo/blade-formatter/issues/703](https://github.com/shufo/blade-formatter/issues/703)

fix: prevent multi-line Comments collapsing into a single line

---

Makefile
README.md

Easy to run and test with Makefile.
Nothing
I wanted to easily execute build, run, test, and debug, so I realized it with Makefile.
https://github.com/shufo/blade-formatter/commit/01a1239a3a5682388020c26913344545f3d861f3
I ran the following command and confirmed that the test passed.
```sh
$ make build
```
```sh
$ make run sample.php
```
```sh
$ make test
...
-----------------------------|---------|----------|---------|---------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
File                         | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s …
```

🧑‍💻 easy execution using Makefile

---

esbuild.ts

This PR updates esbuild config to use latest API interface.
esbuild v17 changed watch option so current config is no longer valid.
Build and run test.

refactor: 💡 update esbuild config to use new esbuild API

---

package.json
yarn.lock

Reverts shufo/blade-formatter#850

fix(deps): revert update dependency @prettier/plugin-php to ^0.20.0

---

.github/workflows/node.yml

Add test setup for node 22.x stable version.
Current stable version for nodejs is 22.x
CI passed.

ci: 🎡 add test setup for node 22.x

---

yarn.lock

This PR bumps js-beautify to 1.15.1

chore: 🤖 bump js-beautify to 1.15.1

---

package.json
yarn.lock

This PR bumps prettier plugin-php dependency to 0.22.4.
0.22.4 fixes some formatting issue.

chore: 🤖 bump @prettier/plugin-php to 0.22.4

---

package.json
yarn.lock

Reverts shufo/blade-formatter#1024

Revert "chore: 🤖 bump vscode-textmate to 9.2.0"
