shufo/blade-formatter

- src/formatter.js
Save the parameter `options` into `this.options` because the function `formatAsHtml` refers to `this.options`.
#6
> Fix indent size behavior

- .github/workflows/node.yml
cache npm modules to optimize yarn installtion
- none
- because every time ci runs yarn installs all modules. it's too heavy
- pray CI to pass and Retry-retry-retry...
> ci(npm): cache npm modules

- __tests__/formatter.test.js
- src/formatter.js
This pr fixes #48 
- #48 
keeping indentation on formatted lines causes padding insert
see test
> fix(formatter): do not insert padding in blankline

- __tests__/formatter.test.js
- src/formatter.js
- src/util.js
fixes #56, fixes #57
This PR fixes behaviour that embedded php tags in original content unexpectedly removed.
see #56, #57
See tests.
> fix: 🐛 preserve embedded php tags in original content

- __tests__/formatter.test.js
- src/util.js
https://github.com/shufo/vscode-blade-formatter/issues/2
Fixes https://github.com/shufo/vscode-blade-formatter/issues/2
Unexpectedly Regexp removes tags between php open tag and blade brackets.
see test
> fix: 🐛 do not remove original php tag

- __tests__/formatter.test.js
- src/util.js
code like below unexpectedly remove tags after blade close expression
```
{{ trans('email.website_title') }}&nbsp;
<a href="mailto:{{ trans('email.website_url') }}">{{ trans('email.website_url') }}</a>
```
will formatted to
```
{{ trans('email.website_title') }}&nbsp;
```
> fix: 🐛 unexpectedly remove tags after blade close expression

- __tests__/formatter.test.js
- src/util.js
fixes bug related to nested function in directive
refs #113 
see tests
> fix: 🐛 regex to match balanced parentheses

- __tests__/formatter.test.js
- src/util.js
forelse directive occurs error on formamt
```php
'Parse Error : syntax error, unexpected \'as\' (T_AS), expecting \')\' on line 1\n\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 1 | \u001b[39m\u001b[33m<\u001b[39m\u001b[33m?\u001b[39mphp forelse($students as $student) \u001b[33m?\u001b[39m\u001b[33m>\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m   | \u001b[39m                       \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m',
```
> fix: 🐛 ignore forelse directive for formatting

- README.md
- __tests__/cli.test.js
- package.json
- src/cli.js
#123 #110
✅ Closes: #123 
This PR adds a feature for stdin support.
stdin support enables communication with other processes more easier.
After this PR merged, `--stdin` option will be enabled.
```bash
cat test.blade.php | ./node_modules/.bin/blade-formatter --stdin
```
> feat: 🎸 support stdin input

- package.json
- src/util.js
- yarn.lock
- prettier 2.0.0 causes some webassembly error if blade-formatter used as external package
```bash
WebAssembly.instantiate(): Import #6 module="env" function="table" error: table import requires a WebAssembly.Table
```
- bump up to ^2.2.0 seems to fixes this error
> feat: 🎸 bump prettier to 2.2.0

- src/vsctm.js
- #177 
- webassembly error occurs on some condition
```bash
WebAssembly.instantiate(): Import #6 module="env" function="table" error: table import requires a WebAssembly.Table
```
- resolve path by require.resolve seems fixes this issue
- used this version on vscode-blade-formatter
> fix: 🐛 resolve path by require.resolve

- __tests__/cli.test.js
- __tests__/fixtures/blade_brace_without_space.blade.php
- __tests__/fixtures/formatted.blade_brace_without_space.blade.php
- src/formatter.js
- src/util.js
This pr fixes format error on brade brace without spaces between braces like below
```blade
<title>{{$user}}{{$name}}</title>
```
It should be format to 
```blade
<title>{{ $user }}{{ $name }}</title>
```
> fix: 🐛 blade brace without space occurs error

- __tests__/cli.test.js
- __tests__/fixtures/escaped_blade_tag.blade.php
- __tests__/fixtures/formatted.edit.blade.php
- __tests__/fixtures/formatted.escaped_blade_tag.blade.php
- __tests__/fixtures/formatted.escaped_bug.blade.php
- src/formatter.js
- src/util.js
> fix: 🐛 do not add line return in unescaped blade brace

- __tests__/formatter.test.js
- src/util.js
- fix: 🐛 echo php expressionn
- test: 💍 add test for php predefined constant echo
- fixes https://github.com/shufo/vscode-blade-formatter/issues/64
> fix: raw php constant expression causes parse error

- __tests__/formatter.test.js
- package.json
- yarn.lock
- feat: 🎸 bump plugin-php to php 8 supported version (wip)
- test: 💍 add test for null safe operator
- This PR will add support for php 8 syntax
- null safe operator
e.g.
```php
{{ $entity->executors->first()?->name() }}
```
- named arguments
e.g.
```php
{{ htmlspecialchars($string, double_encode: false) }}
```
- https://github.com/shufo/vscode-blade-formatter/issues/75
- https://github.com/shufo/vscode-blade-formatter/issues/61
see added tests
> feat: support php 8 syntax

- __tests__/cli.test.js
- __tests__/fixtures/directive_in_scripts_complex.blade.php
- __tests__/fixtures/formatted.directive_in_scripts_complex.blade.php
- src/formatter.js
- refs: https://github.com/shufo/vscode-blade-formatter/issues/47
- fixes indentation problem in directive in script tags like below causes unexpected format error
```blade
@push('scripts')
<script src="{{ asset('backend/plugins/dropzone/dropzone.min.js') }}"></script>
<script>
Dropzone.options.gallery = {
url: "...",
previewTemplate: $("#preview-template").html(),
dictDefaultMessage: "Drop files here or click to select",
addRemoveLinks: true,
uploadMultiple: true,
maxFilesize: 2,
filesizeBase: 1024,
acceptedFiles: "image/jpg,image/jpeg,image/png",
init: function() {
this.renderExistingServerFiles = function(files, fileUrls, response) {
for (const file in files) {
if (Object.hasOwnProperty.call(files, file)) {
const element = files[file];
this.files.push(element); …
```
> fix: 🐛 adjust indent level for directive in scripts

- __tests__/formatter.test.js
- src/util.js
- fix: 🐛 break chained method in directive
- test: 💍 add test for chained method in directive
chained method in directive like below
```blade
"@if (auth()->user()->subscribed('default'))",
```
was unexpectedly break into
```blade
"@if (auth()
->user()
->subscribed('default'))",
```
- https://github.com/shufo/vscode-blade-formatter/issues/53
Expression in directive parenthesis should not break
see tests
> fix: break chained method in directive

- __tests__/cli.test.js
- __tests__/fixtures/case_directive.blade.php
- __tests__/fixtures/formatted.case_directive.blade.php
- __tests__/formatter.test.js
- src/formatter.js
- src/indent.js
CUrrently `@case` directive is unexpectedly formatted as flat structure.
```blade
@switch($i)
@case(1)
First case...
@break
@case(2)
Second case...
@break
@default
Default case...
@endswitch
```
will be formatted as
```blade
@switch($i)
@case(1)
First case...
@break
@case(2)
Second case...
@break
@default
Default case...
@endswitch
```
- fixes: #209
body inside `@case` directive should be indented
see tests
> fix: 🐛 indent body inside case directive #209

- __tests__/formatter.test.js
- src/formatter.js
- src/indent.js
- fix: 🐛 format inline directive in script tag
- refactor: 💡 return if raw content is inlined
- test: 💍 add test for inline directive in script tag
- inline directive like `@json` is not formatted in script tag
- fixes: https://github.com/shufo/vscode-blade-formatter/issues/99
inline directive in script tag also should be formatted
see tests
> fix: format inline directive in script tag

- __tests__/formatter.test.js
- src/indent.js
- `@forelse` directive inside `@if` directive gets unexpected indentation
- fixes: #254
see tests
> fix: 🐛 `@forelse` inside `@if` gets unexpected indentation #254

- .github/workflows/platform-test.yml
- package.json
- src/cli.js
- src/formatter.js
- src/vsctm.js
- yarn.lock
- #262 
- This PR bump vscode-textmate and vscode-oniguruma to support node v16.x
- To support v16.x, loadWASM on cli interface
- Also this PR adds github action to test each platform (macOS, Windows, Ubuntu)
> fix: support node v16.x

- __tests__/cli.test.js
- __tests__/fixtures/formatted.directive_in_scripts.blade.php
- __tests__/fixtures/formatted.directive_in_scripts_complex.blade.php
- __tests__/fixtures/formatted.escaped_bug.blade.php
- __tests__/fixtures/formatted.multiline_blade_comment.blade.php
- __tests__/fixtures/formatted.multiline_templating_string_in_script_tag.blade.php
- __tests__/fixtures/formatted_shorttag.blade.php
- __tests__/fixtures/multiline_templating_string_in_script_tag.blade.php
- __tests__/formatter.test.js
- src/formatter.js
- fix: 🐛 store script tag in blade template
- fix: 🐛 unexpected new line inserted before script closing tag
- fix: 🐛 wrap line attribute behaviour in script tag
- test: 💍 assert multiline templating string behaviour
- #279
- This PR adds behaviour to preserve script tag in blade template
- multiline template string in script tag should preserve its white spaces
- see tests
> fix: templating string indentation behaviour in script tag

- __tests__/cli.test.js
- __tests__/fixtures/formatted.escaped_bug.blade.php
- __tests__/fixtures/formatted.raw_php_tag.blade.php
- __tests__/fixtures/formatted_shorttag.blade.php
- __tests__/fixtures/raw_php_tag.blade.php
- __tests__/formatter.test.js
- jest.config.js
- package.json
- src/formatter.js
- src/util.js
- yarn.lock
- fix: 🐛 preserve original php tag in template #304
- test: 💍 fix formatted result cause formatter behaviour change
- test: 💍 add test for template including raw php tag
- chore: 🤖 add config for jest
- Multiline raw php tag like
```php
<?php
// foo
echo $user
?>
```
gets unexpected indentation when executing format multiple time.
It should be keep indent level even if it formatted multiple time.
- #304
> fix: raw php tag gets unexpected format behaviour

- __tests__/formatter.test.js
- src/util.js
this adds an optional whitespace to the regexes in util.revertDirectives
fixes https://github.com/shufo/blade-formatter/issues/229
a test is included
> fix: disappearing lines with force-expand-multiline

- __tests__/cli.test.js
- __tests__/fixtures/append_tag.blade.php
- __tests__/fixtures/formatted.append_tag.blade.php
- src/indent.js
- fix: 🐛 add `@append` directive as indent end token
- test: 💍 add test for `@append` directive
Currently there is no support for `@append` directive.
- fixes: #313
To support `@append` token.
see tests.
> fix: support `@append` directive

- __tests__/formatter.test.js
- src/formatter.js
- src/indent.js
- src/util.js
do not indent some directives where a second argument makes the endtag needless
Currently those directives with second argument gets an unexpected indent
fixes #318
to fix the indents on @section, @push and @prepend with a second parameter
a test is included
---
i tried it first with a custom prettier plugin to get access to the AST, but had problems with it.
hope you are okey to use `prettier.__debug.parse()`
> fix: bug do not indent @section, @push and @prepend if a second argument is present (#318)

- __tests__/formatter.test.js
- src/formatter.js
✅ Closes: https://github.com/shufo/vscode-blade-formatter/issues/206
- empty class attribute causes unexpected replacement on format
- https://github.com/shufo/vscode-blade-formatter/issues/206
- see tests
> fix: 🐛 empty class attribute cause unexpected replacement

- __tests__/formatter.test.js
- src/formatter.js
✅ Closes: https://github.com/shufo/vscode-blade-formatter/issues/251
Template like below invokes exception because of `@empty` directive
```blade
<script>
var addNewCoin = [
@forelse($coins as $coin)
{
"id": {{ $coin->id }},
"name": "{{ $coin->name }}"
},
@empty
@endforelse
];
</script>
```
- https://github.com/shufo/vscode-blade-formatter/issues/251
- see tests
> fix: 🐛 forelse-empty directive in scripts

- __tests__/formatter.test.js
- src/util.js
case expression adds unnecessary space if expression is string
```blade
@foreach ($items as $item)
@switch($item->status)
@case("status")
// Do something
@break
@endswitch
@endforeach
```
```blade
@foreach ($items as $item)
@switch($item->status)
@case(" status")
// Do something
@break
@endswitch
@endforeach
```
- fixes: https://github.com/shufo/vscode-blade-formatter/issues/274
- see tests
> fix: 🐛 adds unnecessary space on quoted expression

- __tests__/formatter.test.ts
- src/formatter.ts
- src/indent.ts
- fixes: https://github.com/shufo/vscode-blade-formatter/issues/284
- fixes: https://github.com/shufo/vscode-blade-formatter/issues/249
- https://github.com/shufo/vscode-blade-formatter/issues/284
- https://github.com/shufo/vscode-blade-formatter/issues/249
- A character like `<` in conditional expression makes unexpected indent error
- see added tests
> fix: 🐛 indent error in formatting conditional expression

- README.md
- __tests__/cli.test.ts
- __tests__/fixtures/ignore_entire_file_comment.blade.php
- __tests__/formatter.test.ts
- src/formatter.ts
- This PR adds feature to disable formatting in a file by adding comments.
To disable multiline:
```blade
{{-- blade-formatter-disable --}}
foo
{{-- blade-formatter-enable --}}
```
To disable format on a specific line:
```blade
{{-- blade-formatter-disable-next-line --}}
foo
```
To disable format on an entire file, put `{{-- blade-formatter-disable --}}` on top of the file:
```blade
{{-- blade-formatter-disable --}}
foo
```
- #395 
- Sometimes it is required to ignore specific lines in a file instead of ignore entire file.
- see tests
> feat: 🎸 add ignore statement for disable formatting

- __tests__/formatter.test.ts
- src/formatter.ts
- This PR fixes https://github.com/shufo/vscode-blade-formatter/issues/269
- https://github.com/shufo/vscode-blade-formatter/issues/269
To support `@{{~}}` syntax.
see: https://laravel.com/docs/5.5/blade#blade-and-javascript-frameworks
see tests
> fix: 🐛 `@{{~}}` syntax occurs parse error

- __tests__/formatter.test.ts
- src/indent.ts
- This PR fixes https://github.com/shufo/vscode-blade-formatter/issues/304
- https://github.com/shufo/vscode-blade-formatter/issues/304
`@slot` directive without `@endslot` directive gets incorrect formatting
e.g.
```blade
@component('components.article.intro')
@slot('date', $article->formatDate)
@slot('read_mins', $article->readTime)
@if ($author)
@slot('authors', [['link' => $author_link, 'name' => $author]])
@endif
@slot('intro_text')
{!! $article->introduction !!}
@endslot
@endcomponent
```
see tests
> fix:  `@slot` without `@endslot` incorrect formatting

- __tests__/cli.test.ts
- __tests__/fixtures/syntax.error.blade.php
- __tests__/formatter.test.ts
- src/cli.ts
- src/errors/formatError.ts
- src/main.ts
- fix: 🐛 format from stdin results always exit code 0
- test: 💍 add test for error on stdin option
- test: 💍 add test for error throw
This PR fixes stdin option behaviour.
Currently formatting with `--stdin` option always returns exit code 0 even if error occurs, but it's unexpected behaviour.
If something occurs while formatting (Syntax Error etc...) it should returns exit code 1.
see tests
> fix: 🐛 format from stdin results always exit code 0

- __tests__/formatter.test.ts
- src/formatter.ts
- fix: 🐛 inline nested parenthesis have unexpected formatting
- test: 💍 add test for inline nested parenthesis
This PR fixes #350 
- #350 
Inline nested parenthesis should be keep its form
see tests
> fix: 🐛  inline nested parenthesis have unexpected formatting

- __tests__/formatter.test.ts
- src/util.ts
✅ Closes: #340
see #340
- #340
Three more nested parenthesis should be allowed in directive expression
see tests
> fix: 🐛 hangs when 3 more nested parenthesis used in directive

- __tests__/fixtures/formatted.escaped_blade_tag.blade.php
- __tests__/fixtures/formatted_inline_php_tag.blade.php
- __tests__/formatter.test.ts
- src/formatter.ts
This PR adds new behaviour, adds line break before and after directives automatically.
e.g.  complex inlined directive like below
```blade
<div>
@if ($user) @if ($condition) aaa @endif
@endif
@can('edit') bbb
@endcan
@auth('user') ccc
@endauth
</div>
<div>@foreach($users as $user) @foreach($shops as $shop) {{ $user["id"] . $shop["id"] }} @endforeach @endforeach</div>
<div>@if($users) @if($shops) @foreach($shops as $shop) {{ $user["id"] . $shop["id"] }} @endforeach @endif @endif</div>
@isset($user) aaa @endisset
```
```blade
<div>
@if ($user)
@if ($condition) aaa @endif
@endif
@can('edit')
bbb
@endcan
@auth('user')
ccc
@endauth
</div>
<div>
@foreach ($users as $user)
@foreach ($shops as $shop)
{{ $user['id'] . $shop['id'] }}
@endforeach
@endforeach
</div>
<div>
@if …
```
> feat: auto line break around directives

- __tests__/formatter.test.ts
- src/formatter.ts
- fix: 🐛 json directive adds unexpected whitespace
- test: 💍 add test for json directive
This PR fixes `@json` directive bug that adds unexpected whitespace if quotation used in `@json` directive is same as outer quotation. 
e.g. 
```blade
<div data-single-quote='@json('string with single quote')'>
</div>
```
```blade
<div data-single-quote='@json(' string with single quote')'>
</div>
```
fixed behaviour keeps format even if quotation mark is same.
- fixes: https://github.com/shufo/blade-formatter/issues/210
- fixes: https://github.com/shufo/blade-formatter/issues/334
see tests
> fix: 🐛 json directive adds unexpected whitespace

- README.md
- src/indent.ts
Blade formatter was splitting the `@endforeach` directive into
`
@endfor
each
`
causing a fatal error, It seems like the order of keywords was wrong and @endfor was matching before @endforeach, there might be other directives in the list which suffer from the same problem, maybe a better fix would using a wordmatch, even though reordering the directives fixed the problem in my case.
> fix: endforelse causing formatting error

- __tests__/formatter.test.ts
- src/formatter.ts
- feat: 🎸 auto line breaking around else if directives
- test: 💍 add test for else if line breaking
- fix: 🐛 auto line break around else directive
This PR adds feature to auto line breaking around else/else if directives.
e.g.
```blade
@if (count($users) === 1)
Foo
@elseif (count($users) > 1)Bar
@elseif (count($users) > 2) Bar2
@else Baz @endif
```
will format into 
```blade
@if (count($users) === 1)
Foo
@elseif (count($users) > 1)
Bar
@elseif (count($users) > 2)
Bar2
@else
Baz
@endif
```
- #474 
Directives like `@else`, `@elseif`, and `@elsecan` should have automatic line breaks as well.
see tests
> feat: 🎸 auto line breaking around else/ else if directives

- __tests__/formatter.test.ts
- src/formatter.ts
- fix: 🐛 line break does not occur around html tag
- refactor: 💡 add description comment
- test: 💍 add test for line breaking with html tag
This PR adds behaviour to breaking lines around html tag.
e.g.
```blade
<div>
<div>@can('auth')
foo @elsecan('aaa') bar @endcan</div>
<div>@foreach($users as $user)
{{$user}} bar @endforeach</div></div>
<div>@if (count($users) === 1) Foo @elseif (count($users) > 1)Bar @elseif (count($users) > 2) Bar2 @else Baz @endif</div>
```
```blade
<div>
<div>
@can('auth')
foo
@elsecan('aaa')
bar
@endcan
</div>
<div>
@foreach ($users as $user)
{{ $user }} bar
@endforeach
</div>
</div>
<div>
@if (count($users) === 1)
Foo
@elseif (count($users) > 1)
Bar
@elseif (count($users) > 2)
Bar2
@else
Baz
@endif
</div>
```
- #483
Directives enclosed in html …
> fix: line breaking around html tag

- __tests__/formatter.test.ts
- src/formatter.ts
- fix: 🐛 inlined php doc gets unexpected line break
- test: 💍 add test for inlined php doc
This PR fixes the behaviour that inlined php doc gets expected line break
e.g. 
```blade
<?php /** @var \App\Models\Game $game */ ?>
```
```blade
<?php /** @var \App\Models\Game $game */ 
?>
```
- fixes: #493
see tests
> fix: 🐛 inlined php doc gets unexpected line break

- README.md
- __tests__/cli.test.ts
- __tests__/fixtures/formatted.tailwindcss.blade.php
- __tests__/fixtures/runtimeConfig/.bladeformatterrc.sort-tailwind-classes
- __tests__/fixtures/tailwindcss.blade.php
- __tests__/formatter.test.ts
- package.json
- src/cli.ts
- src/formatter.ts
- src/main.ts
- yarn.lock
This PR adds feature to sort tailwindcss classes automatically.
```yaml
$ blade-formatter --sort-tailwindcss-classes example.blade.php
$ blade-formatter --sort-classes example.blade.php
```
```js
new Formatter({ sortTailwindcssClasses: true }).formatContent(content).then((result: string) => {
console.log(result);
});
```
```json
{
"sortTailwindcssClasses": true
}
```
This is a breaking behavior change, so I'll offer it as a opt-in option at first, and once we're sure it's safe to use, I'll release a version of it as a breaking change.
- closes: #496 
There is needs to sort tailwindcss classes in blade file.
see tests
> feat: sort tailwindcss classes automatically

- __tests__/fixtures/formatted.blade_brace_without_space.blade.php
- __tests__/formatter.test.ts
- src/formatter.ts
This PR fixes indentation behaviour that include directive does not indent parameters
- fixes: #501 
- see #501 
see tests
> fix: 🐛 include directive does not indent parameters

- __tests__/formatter.test.ts
- src/formatter.ts
✅ Closes: #504
This PR fixes `@include` directive behaviour that include directive with long view name adds unnecessary comma causing syntax error.
- fixes #504 
see tests
> fix: 🐛 formatted include directive adds unnecessary comma

- __tests__/formatter.test.ts
- src/formatter.ts
✅ Closes: #508
This PR fixes #508 that inline script tag with DOM element removes its previous element.
```blade
<p>foo</p><p>bar</p><script>document.write("buz");</script><p>blah</p>
```
```blade
<p>foo</p>
<script>
document.write("buz");
</script><p>blah</p>
```
- fixes: #508
inline script tag with DOM element should keep its content
see tests
> fix: 🐛 inilne script tag removes previous DOM

- __tests__/formatter.test.ts
- src/formatter.ts
- src/indent.ts
This PR adds support for `@selected`, `@disabled` and `@checked` directive
Laravel 9 added new directive `@selected`, `@disabled` and `@checked` 
https://laravel.com/docs/9.x/blade#checked-and-selected
see tests
> feat: add support for selected, disabled and checked directive

- __tests__/formatter.test.ts
- src/formatter.ts
- fix: 🐛 curly braces with long expression gets unexpected result
- test: 💍 add test for curly braces with long expression
This PR fixes the behavior that caused unexpected results for braces in certain conditions.
Currently, unexpected formatting happens when curly braces containing long expressions.
e.g.
```blade
<a href="{{ $relatedAuthority->id }}" class="no-border"
itemprop="{{ $author->isCorporateBody() ?
($relatedAuthority->isCorporateBody() ? 'knowsAbout' : 'member') :
($relatedAuthority->isCorporateBody() ? 'memberOf' : 'knows') }}">
<strong>{{ formatName($relatedAuthority->name) }}</strong>
<i class="icon-arrow-right"></i>
</a><br>
```
```blade
<a href="{{ $relatedAuthority->id }}"
class="no-border"
itemprop="{{ …
```
> fix: curly braces with long expression gets unexpected result

- __tests__/formatter.test.ts
- src/formatter.ts
This PR fixes the behaviour that whitespace sensitive tags (like `textarea`, `pre`) gets unexpectedly formatted.
- fixes: https://github.com/shufo/vscode-blade-formatter/issues/357
Tags like `textarea`, `pre` should keep its content unformatted.
see tests
> fix: 🐛 whitespace sensitive tag gets formatted unexpectedly

- __tests__/formatter.test.ts
- src/formatter.ts
This PR fixes behavior of characters preventing tailwindcss class reordering.
- fixes: https://github.com/shufo/prettier-plugin-blade/issues/33
Any character should be able to reordering tailwindcss classes
see tests
> fix: 🐛 some character prevent reordering of tailwindcss classes

- __tests__/formatter.test.ts
- src/formatter.ts
This PR fixes the behaviour that class sorting fails when blade braces are mixed in classes.
none
It should be sortable even if blade braces are mixes in classes.
see tests
> fix: 🐛 class sorting fails when blade braces mixed in classes

- __tests__/cli.test.ts
- __tests__/fixtures/component_attribute.blade.php
- __tests__/fixtures/formatted.component_attribute.blade.php
- src/formatter.ts
- fix: 🐛 blade component attribute indents forever
- test: 💍 add test for component attribute
This PR fixes #541
- #541
Blade component with attribute should keep its indent position.
e.g.
```blade
<x-forms.radios legend="Meeting Schedule" name="meeting_type" value="single" v-model="form.meeting_type"
:inline="true" :options="[
'single' => ['label' => 'Default'],
'series' => ['label' => 'Recurring meeting'],
'scheduler' => ['label' => 'Find a meeting date'],
]" />
```
see tests
> fix: multiline blade component attribute indents forever

- __tests__/fixtures/formatted.component_attribute.blade.php
- __tests__/formatter.test.ts
- src/formatter.ts
- fix: 🐛 colon prefixed attribute gets unexpected format
- test: 💍 fix test case to follow current behaviour
- test: 💍 add test case for colon prefixed attribute
This PR fixes #552
- #552
No format should be applied except for component attributes beginning with `x-`.
see tests
> fix: colon prefixed attribute may cause unexpected format

- __tests__/fixtures/formatted.component_attribute.blade.php
- __tests__/formatter.test.ts
- src/formatter.ts
- fix: 🐛 shorthand bindings gets unexpected indentation
- test: 💍 fix test case to follow current behaviour
- test: 💍 add test case for shorthand bindings
This PR fixes #557
- #557
- fixes: https://github.com/shufo/vscode-blade-formatter/issues/402
Shorthand binding should also be handled correctly.
see tests
> fix: shorthand bindings gets unexpexted indentation

- __tests__/formatter.test.ts
- src/indent.ts
✅ Closes: #542
This PR fixes #542
Template like below preserve its format
```blade
@set($myVariableWithVeryVeryVeryVeryVeryLongName = ($myFirstCondition || $mySecondCondition) ? 'My text' : 'My alternative text')
```
- #542
see tests
> fix: 🐛 prevent set directive to be wrapped

- __tests__/formatter.test.ts
- src/formatter.ts
- src/indent.ts
✅ Closes: https://github.com/shufo/prettier-plugin-blade/issues/58
This PR fixes https://github.com/shufo/prettier-plugin-blade/issues/58.
```blade
<div>
<div>
@component(     'path.to.component',[
'title' => 'My title',
'description' => '',
'header' => [
'transparent' => true,
],
'footer' => [
'hide' => true,
],
])
<div>
some content
</div>
@endcomponent
</div>
</div>
```
```blade
<div>
<div>
@component('path.to.component',
[
'title' => 'My title',
'description' => '',
'header' => [
'transparent' => true,
],
'footer' => [
'hide' => true,
],
])
<div>
some content
</div>
@endcomponent
</div>
</div>
```
- https://github.com/shufo/prettier-plugin-blade/issues/58
We should keeep indentation of component directive arguments.
see tests
> fix: 🐛 component directive argument lose indentation

- __tests__/formatter.test.ts
- src/formatter.ts
- fix: 🐛 long inline blade braces adds unexpected line break
- test: 💍 add test for long inline blade braces
This PR fixes https://github.com/shufo/vscode-blade-formatter/issues/409
- https://github.com/shufo/vscode-blade-formatter/issues/409
Long line inline blade braces should keep its format.
see tests
> fix: 🐛 long inline blade braces adds unexpected line break

- __tests__/formatter.test.ts
- src/formatter.ts
- src/util.ts
- fix: 🐛 dollar sign may cause formatting errors
This PR fixes #565.
Formatting error occurs if dollar sign exists between directives.
- #565
Even when dollar signs are present, they should not be interpreted as special symbols for `prototype.replace` function.
see tests
> fix: 🐛 dollar sign may cause formatting errors

- __tests__/formatter.test.ts
- src/formatter.ts
✅ Closes: https://github.com/shufo/prettier-plugin-blade/issues/65
This PR fixes https://github.com/shufo/prettier-plugin-blade/issues/65
- https://github.com/shufo/prettier-plugin-blade/issues/65
Livewire tag attributes should be formatted as php expression.
see tests
> fix: 🐛 livewire tag causes unexpected formatting

- __tests__/formatter.test.ts
- src/formatter.ts
- fix: 🐛 multiline blade brace results in unexpected formatting
- test: 💍 add test case for multiline blade brace
This PR fixes #581
- #581
Even a multi-line blade brace should not throws an error
see tests
> fix: multi line blade brace results in unexpected formatting

- __tests__/formatter.test.ts
- src/formatter.ts
- fix: 🐛 timeout on isset~endif directive in html tag
- test: 💍 add test for isset~endif directive in html tag
This PR fixes #585
- #585
It should not timeout on `@isset~@endif` directive exists in html tag
see tests
> fix: timeout on @isset~@endif directive in html tag

- __tests__/formatter.test.ts
- src/formatter.ts
✅ Closes: https://github.com/shufo/vscode-blade-formatter/issues/417
This PR fixes https://github.com/shufo/vscode-blade-formatter/issues/417
When the content of class attribute is empty and sortTailwindcssClass option is true, the regular expression matches unexpected result.
- https://github.com/shufo/vscode-blade-formatter/issues/417
Formatter should keep its format even if the class string is empty and the sort option of tailwindcss class is true
see tests
> fix: 🐛 empty class string results in unexpected formatting

- __tests__/formatter.test.ts
- src/formatter.ts
✅ Closes: https://github.com/shufo/vscode-blade-formatter/issues/421
This PR fixes https://github.com/shufo/vscode-blade-formatter/issues/421
- https://github.com/shufo/vscode-blade-formatter/issues/421
Current regex to extract class attribute unexpectedly matching `x-bind:class` attribute
see tests
> fix: 🐛 format broken by x-bind:class when class sort enabled

- __tests__/formatter.test.ts
- src/indent.ts
✅ Closes: https://github.com/shufo/prettier-plugin-blade/issues/80
This PR fixes https://github.com/shufo/prettier-plugin-blade/issues/80
- https://github.com/shufo/prettier-plugin-blade/issues/80
Currently, nested `unless` condition expressions lead to unexpected formatting results
see tests
> fix: 🐛 nested unless condition results in unexpected format

- __tests__/formatter.test.ts
- src/indent.ts
✅ Closes: https://github.com/shufo/vscode-blade-formatter/issues/425
This PR fixes https://github.com/shufo/vscode-blade-formatter/issues/425
- https://github.com/shufo/vscode-blade-formatter/issues/425
`@forelse~@empty~@endforelse` directive should be peroperly formatted even if they are in `@forelse~@if~@endif~@empty~@endforelse`
see tests
> fix: 🐛 nested forelse directive results in unexpected format

- __tests__/formatter.test.ts
- src/formatter.ts
- src/indent.ts
✅ Closes: https://github.com/shufo/vscode-blade-formatter/issues/430
This PR fixes https://github.com/shufo/vscode-blade-formatter/issues/430
- https://github.com/shufo/vscode-blade-formatter/issues/430
Unexpected Syntax Error occurs when [CSS at-rule](https://developer.mozilla.org/en-US/docs/Web/CSS/At-rule) is recognized as a custom directive.
see tests
> fix: 🐛 at-rules of css results in Syntax Error

- __tests__/fixtures/formatted.append_tag.blade.php
- __tests__/fixtures/formatted.multiline_blade_comment.blade.php
- __tests__/fixtures/formatted.overwrite_tag.blade.php
- __tests__/fixtures/formatted_shorttag.blade.php
- __tests__/formatter.test.ts
- src/formatter.ts
✅ Closes: https://github.com/shufo/vscode-blade-formatter/issues/385
This PR fixes https://github.com/shufo/vscode-blade-formatter/issues/385
- https://github.com/shufo/vscode-blade-formatter/issues/385
It should not insert new line at end of style tag.
see tests
> fix: 🐛 new line inserted at end of style tag

- __tests__/fixtures/formatted_shorttag.blade.php
- __tests__/formatter.test.ts
- src/formatter.ts
✅ Closes: https://github.com/shufo/vscode-blade-formatter/issues/414, https://github.com/shufo/vscode-blade-formatter/issues/432
This PR fixes https://github.com/shufo/vscode-blade-formatter/issues/414, https://github.com/shufo/vscode-blade-formatter/issues/432
- fixes: https://github.com/shufo/vscode-blade-formatter/issues/414
- fixes: https://github.com/shufo/vscode-blade-formatter/issues/432
textarea tag wrapping results in unexpected indent when wrapAttribute option (`force-aligned`, `aligned-multiple`) specified.
see tests
> fix: 🐛 unexpected result when wrap attributes option specified

- __tests__/formatter.test.ts
- src/formatter.ts
Sometimes arrow like identifier `=>` in html attribute results in unexpected format
e.g.
```blade
<script src="1 => 2">
const a = 1;
</script>
```
see tests
> fix: 🐛 arrow indentifier sometimes results in unexpected format

- __tests__/fixtures/formatted.blade_brace_without_space.blade.php
- __tests__/fixtures/formatted_shorttag.blade.php
- __tests__/formatter.test.ts
- src/formatter.ts
- fix: 🐛 multiline html attribute keep indenting
- test: 💍 fix test cases to follow current behaviour
This PR adds protection for html attributes that is not formatted yet.
- https://github.com/shufo/prettier-plugin-blade/issues/86
Multiline html attribute keep indenting.
see tests
> fix: preserve html attributes

- __tests__/formatter.test.ts
- src/formatter.ts
✅ Closes: https://github.com/shufo/vscode-blade-formatter/issues/443
This PR fixes https://github.com/shufo/vscode-blade-formatter/issues/443
- fixes: https://github.com/shufo/vscode-blade-formatter/issues/443
Blade directive treat entire parameter as string.
e.g. `@popper(This works)` will pass string parameter `'This works'` to directive function.
```php
Blade::directive('popper', function (string $text) {
// $text => 'This works'
return $text;
});
// even if string contains `,`, directive will pass entire parameter as string
@popper(This works, 2nd args)
Blade::directive('popper', function (string $text) {
// $text => 'This works, 2nd args'
return $text;
});
```
see tests
> fix: 🐛 raw string in custom directive results syntax error

- __tests__/formatter.test.ts
- src/formatter.ts
✅ Closes: https://github.com/shufo/vscode-blade-formatter/issues/440
This PR fixes https://github.com/shufo/vscode-blade-formatter/issues/440
- https://github.com/shufo/vscode-blade-formatter/issues/440
Multi-lined script tag should be indent even if wrapping option specified
see tests
> fix: 🐛 script tag attributes are unindented when multi-lined

- __tests__/formatter.test.ts
- src/formatter.ts
✅ Closes: https://github.com/shufo/vscode-blade-formatter/issues/474
This PR fixes https://github.com/shufo/vscode-blade-formatter/issues/474
- https://github.com/shufo/vscode-blade-formatter/issues/474
Regular expressions are causing unintended matching and causing stuck.
see tests
> fix: 🐛 sometimes equal symbols cause formatting to get stuck

- __tests__/fixtures/formatted.edit.blade.php
- __tests__/formatter.test.ts
- src/formatter.ts
- fix: 🐛 indentation removed when raw blade brace is multi-lined
- test: 💍 fix test case to follow current behaviour
- test: 💍 add test for raw blade braces
This PR fixes https://github.com/shufo/vscode-blade-formatter/issues/489
- https://github.com/shufo/vscode-blade-formatter/issues/489
Multi-lined raw blade brace should keep its indentation.
see tests
> fix: indentation removed when raw blade brace is multi-lined

- __tests__/formatter.test.ts
- src/formatter.ts
This PR fixes https://github.com/shufo/vscode-blade-formatter/issues/491
- https://github.com/shufo/vscode-blade-formatter/issues/491
The prettier php plugin using in this formatter inserts comma at end of parentheses unexpectedly.
see tests
> fix: 🐛 nested condition inserts unexpected comma

- __tests__/formatter.test.ts
- src/formatter.ts
This PR refactor brace braces preservation behaviour.
Currently a blade brace that includes a space will be preserved including the extra space, which may lead to unexpected behavior when formatting.
see tests
> refactor: 💡 do not preserve unnecessary spaces in brace braces

- __tests__/formatter.test.ts
- src/util.ts
This PR fixes https://github.com/shufo/vscode-blade-formatter/issues/501
- https://github.com/shufo/vscode-blade-formatter/issues/501
Unexpected line break occur if given variabe to foreach is calling method from object
see tests
> fix: 🐛 as keyword breaks line if calling method

- README.md
Added blade-formatter as a builtin formatter in null-ls.nvim - [#963](https://github.com/jose-elias-alvarez/null-ls.nvim/pull/963)
> docs: add null-ls extension link

- __tests__/formatter.test.ts
- src/formatter.ts
✅ Closes: #666
This PR fixes #666
- #666
Currently script tag with not js code will break its format.
So format as JS code only when `type="text/javascript"` or type is not specified, otherwise do nothing.
see tests
> fix: 🐛 unexpected format results when script tag type is not js

- __tests__/formatter.test.ts
- src/formatter.ts
✅ Closes: #669
This PR fixes #669
- #669
see #669
see tests
> fix: 🐛 escaped quote in raw php directive breaks indentation

- __tests__/formatter.test.ts
- src/regex.ts
✅ Closes: #672
This PR fixes #672
- #672
Catastrophic regex backtrack happens when unclosed directive parentheses exists.
see tests
> fix: 🐛 hangs when unclosed directive parentheses exists

- .github/workflows/platform-test.yml
- __tests__/cli.test.ts
- src/cli.ts
- tsconfig.json
This PR improves CLI outputs.
- help option displays the name and version of the tool and URL to the repository
```bash
$  blade-formatter --help
blade-formatter 1.26.17
An opinionated blade template formatter for Laravel.
Usage: blade-formatter [options] [file glob | ...]
```
- When a non-existent option or other option is passed, explicitly stating that the option does not exist.
```bash
$  ./node_modules/.bin/blade-formatter test.blade.php --unknwon
error: Unknown argument: unknwon
Usage:  blade-formatter [options] [file glob | ...]
For more information try --help
```
When I looked at other CLI tools, I thought the above things were missing.
see tests
> feat: improve CLI output

- __tests__/formatter.test.ts
- src/util.ts
✅ Closes: #686
This PR fixes #686
- #686
prettier plugin-php puts a comma before the last parenthesis when the method is chained.
see tests
> fix: 🐛 syntax error on chained method

- __tests__/formatter.test.ts
- src/formatter.ts
This PR fixes https://github.com/shufo/vscode-blade-formatter/issues/536
- https://github.com/shufo/vscode-blade-formatter/issues/536
Currently elseif statement in script tag is formatted with line break.
see tests
> fix: 🐛 elseif statement in script tag gets unexpected format

- __tests__/formatter.test.ts
- src/formatter.ts
This PR fixes https://github.com/shufo/vscode-blade-formatter/issues/525.
Inlined directive lost its content if tailwindcss class sorting is enabled.
- https://github.com/shufo/vscode-blade-formatter/issues/525
tailwind css class sorting conflicts inline directive formatting.
see tests
> fix: 🐛 inline directive issue with tailwind class sorting

- __tests__/formatter.test.ts
- src/formatter.ts
✅ Closes: https://github.com/shufo/prettier-plugin-blade/issues/138
This PR fixes https://github.com/shufo/prettier-plugin-blade/issues/138
- https://github.com/shufo/prettier-plugin-blade/issues/138
Incorrect escaping of quote when using html tags within `@php` ~ `@endphp` directive
see tests
> fix: 🐛 invalid quote type when html tag used in php directive

- .github/workflows/node.yml
- README.md
- __tests__/cli.test.ts
- __tests__/fixtures/runtimeConfig/tailwind/.bladeformatterrc.json
- __tests__/fixtures/runtimeConfig/tailwind/formatted.index.blade.php
- __tests__/fixtures/runtimeConfig/tailwind/index.blade.php
- __tests__/fixtures/runtimeConfig/tailwind/tailwind.config.example.js
- __tests__/fixtures/tailwind/formatted.index.blade.php
- __tests__/fixtures/tailwind/index.blade.php
- __tests__/fixtures/tailwind/tailwind.config.example.js
- __tests__/fixtures/tailwind/tailwind.config.js
- __tests__/fixtures/tailwind/tailwind.config.unresolvable.js
- __tests__/formatter.test.ts
- codecov.yml
- package.json
- src/cli.ts
- src/formatter.ts
- src/main.ts
- src/runtimeConfig.ts
- yarn.lock
This PR adds 
- `tailwindcssConfigPath`, `tailwindcssConfig` option for formatter.\n
- `--tailwindcss-config-path` for CLI option.
- https://github.com/shufo/vscode-blade-formatter/issues/554
tailwind config `tailwind.config.js` should respect when `sortTailwindcssClasses` option is enabled.
see tests
> feat:  add option for tailwindcss configuration 

- __tests__/formatter.test.ts
- src/formatter.ts
This PR fixes https://github.com/shufo/vscode-blade-formatter/issues/563
- https://github.com/shufo/vscode-blade-formatter/issues/563
see tests
> fix: 🐛 timeout occur when unclosed quote exists in php block

- __tests__/formatter.test.ts
- src/formatter.ts
- src/indent.ts
This PR fixes https://github.com/shufo/vscode-blade-formatter/issues/565
- https://github.com/shufo/vscode-blade-formatter/issues/565
It should indent the inside of json directives even if they are multiple lines.
see tests
> fix: 🐛 json directive is not indented when it is multi-line

- README.md
- __tests__/cli.test.ts
- __tests__/fixtures/formatted.no_php_syntax_check.blade.php
- __tests__/fixtures/no_php_syntax_check.blade.php
- __tests__/fixtures/runtimeConfig/noPhpSyntaxCheck/.bladeformatterrc
- __tests__/fixtures/runtimeConfig/noPhpSyntaxCheck/formatted.index.blade.php
- __tests__/fixtures/runtimeConfig/noPhpSyntaxCheck/index.blade.php
- __tests__/formatter.test.ts
- src/cli.ts
- src/formatter.ts
- src/main.ts
- src/runtimeConfig.ts
- src/util.ts
- refactor: 💡 add union type BladeFormatterOption
- feat: 🎸 add option `--no-php-syntax-check`
- test: 💍 add tests for no php syntax check option
- refactor: 💡 change the name of parameter
This PR adds feature to disable php syntax check.
- closes: #691
Blade expression allows arbitaly string to its arguments like:
```blade
{{ 'john' | ucfirst | substr:0,1 }}
```
Because blade treat arguments as literal strings.  
So it's up to directive implementation.
Blade Formatter normally treats the representation in the Blade's Directive as PHP because it's formattable.
But this behavior cannot be support the directives that implementing custom syntax.
So I implemented this.
see tests
> feat: option to disable php syntax check

- __tests__/formatter.test.ts
- src/formatter.ts
This PR fixes behaviour of php directive on top level.
- fixes: https://github.com/shufo/vscode-blade-formatter/issues/524
At first, I thought it would be better not to indent along PSR-2, but since the blade directive itself is not related PSR-2, I changed this behavior for consistency.
see tests
> fix: indent inside of php directive on top level

- __tests__/formatter.test.ts
- src/formatter.ts
This PR fixes #736
- #736
It should keep indentation even if raw php tag includes multi-line comment.
see tests
> fix: 🐛 inconsistent multi-line comment indent in raw php tag

- README.md
- src/cli.ts
- src/formatter.ts
- src/main.ts
- src/runtimeConfig.ts
- src/util.ts
Add option for the EOL character.
Add a cli (`end-of-line`) and config (`endOfLine`) option to use a specific end of line character or characters. 
By default, if no option is specified, we still use the `os.EOL` character
> feat: add option for end of line character(s)

- __tests__/formatter.test.ts
- src/comment.ts
- src/formatter.ts
This PR fixes https://github.com/shufo/prettier-plugin-blade/issues/166
- https://github.com/shufo/prettier-plugin-blade/issues/166
Comment block in raw/directive php block should keep its indentation.
see tests
> fix: 🐛 unexpected indent on raw php comment block

- __tests__/formatter.test.ts
- src/formatter.ts
✅ Closes: https://github.com/shufo/vscode-blade-formatter/issues/647
This PR fixes https://github.com/shufo/vscode-blade-formatter/issues/647
- https://github.com/shufo/vscode-blade-formatter/issues/647
see tests
> fix: 🐛 body of formField directive does not indent

- __tests__/formatter.test.ts
- src/formatter.ts
This PR fixes https://github.com/shufo/vscode-blade-formatter/issues/643
- https://github.com/shufo/vscode-blade-formatter/issues/643
see tests
> fix: 🐛 unexpected comma is inserted before closing parentheses

- Dockerfile
Hello, thanks for this useful software!
1. Changed python source in Dockerfile.
2. Changed npm install to yarn install in Dockerfile.
nothing
1. Changed python source in Dockerfile.
python seems to have been discontinued and changed to python3.
ref: https://github.com/docker-library/docker/issues/240
```sh
/ # apk add --update --no-cache git python gcc g++ make
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/aarch64/APKINDEX.tar.gz
ERROR: unable to select packages:
python (no such package):
required by: world[python]
```
2. Changed npm install to yarn install in Dockerfile.
I'm not very familiar with npm, sorry if it's a wrong fix.
```sh
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve …
```
> Fix Dockerfile to work, Change python source, Change from npm to yarn

- __tests__/cli.test.ts
- __tests__/fixtures/formatted.edit.blade.php
- __tests__/formatter.test.ts
- package.json
- yarn.lock
- chore: 🤖 bump js-beautify to 1.14.8
- test: 💍 fix test cases to follow current behaviour
This PR bumps `js-beautify` to 1.14.8
js-beautify to 1.14.8 added new option
see tests
> feat: bump js-beautify to 1.14.8

- README.md
- __tests__/cli.test.ts
- __tests__/fixtures/runtimeConfig/wrapAttributesMinAttrs/.bladeformatterrc.json
- __tests__/fixtures/runtimeConfig/wrapAttributesMinAttrs/formatted.index.blade.php
- __tests__/fixtures/runtimeConfig/wrapAttributesMinAttrs/index.blade.php
- __tests__/fixtures/snapshots/wrap_attributes_min_attrs.snapshot
- __tests__/formatter.test.ts
- src/cli.ts
- src/formatter.ts
- src/main.ts
- src/runtimeConfig.ts
- feat: 🎸 add option `--wrap-attributes-min-attrs`
- test: 💍 add tests for wrapAttributesMinAttrs option
This PR adds option `--wrap-attributes-min-attrs`
`js-beautify` adds option `--wrap-attributes-min-attrs` in recent version.
see tests
> feat: add option `--wrap-attributes-min-attrs`

- __tests__/formatter.test.ts
- src/formatter.ts
This PR fixes the problem of https://github.com/shufo/vscode-blade-formatter/issues/727
- https://github.com/shufo/vscode-blade-formatter/issues/727
see tests
> fix: 🐛 script does not format when type is module

- README.md
- __tests__/cli.test.ts
- __tests__/fixtures/argumentTest/indentInnerHtml/formatted.index.blade.php
- __tests__/fixtures/argumentTest/indentInnerHtml/index.blade.php
- __tests__/fixtures/runtimeConfig/indentInnerHtml/.bladeformatterrc.json
- __tests__/fixtures/runtimeConfig/indentInnerHtml/formatted.index.blade.php
- __tests__/fixtures/runtimeConfig/indentInnerHtml/index.blade.php
- __tests__/fixtures/snapshots/indent_inner_html.snapshot
- src/cli.ts
- src/formatter.ts
- src/main.ts
- src/runtimeConfig.ts
- feat: 🎸 add option `--indent-inner-html`
- test: 💍 add test for indentInnerHtml option
This PR adds option `--indent-inner-html`
- https://github.com/shufo/prettier-plugin-blade/issues/219
This type of formatting option was requested several times.
js-beautify option `--indent-inner-html` option solves this.
see tests
> feat: add option `--indent-inner-html`

- README.md
- src/cli.ts
- src/formatter.ts
- src/main.ts
- src/runtimeConfig.ts
Adding the functionality from the pull request title as an option for the Blade Formatter, modifying the behaviour of [html-beautify](https://github.com/beautify-web/js-beautify#css--html) with the extra liners option as array..
https://github.com/shufo/blade-formatter/issues/842
I think external code formatting, even if opinionated, should be flexible enough to fit the settings one can achieve with native IDE formatting, especially if it improves them. So one gaines more formatting features without losing those already being used to.
Test Suites: 7 passed, 7 total
Tests:           299 passed, 299 total
Snapshots: 0 total
Time:           38.94 s
> added support for html-beautify extra liners option

- __tests__/fixtures/snapshots/unmatched_xslot_close_tag.snapshot
- __tests__/formatter.test.ts
- src/formatter.ts
- src/util.ts
This PR fixes https://github.com/shufo/blade-formatter/issues/851
- https://github.com/shufo/blade-formatter/issues/851
Laravel allows unbalanced closing x-slot tag. So we should match <x-slot:~> tag to closing </x-slot> tag on indent.
see tests
> fix: 🐛 unbalanced x-slot tag behaviour

- __tests__/cli.test.ts
- __tests__/fixtures/argumentTest/trailingCommaPhp/formatted.index.blade.php
- __tests__/fixtures/argumentTest/trailingCommaPhp/index.blade.php
- __tests__/fixtures/runtimeConfig/trailingCommaPhp/.bladeformatterrc
- __tests__/fixtures/runtimeConfig/trailingCommaPhp/formatted.index.blade.php
- __tests__/fixtures/runtimeConfig/trailingCommaPhp/index.blade.php
- __tests__/fixtures/snapshots/trailing_comma_php.snapshot
- src/cli.ts
- src/formatter.ts
- src/main.ts
- src/runtimeConfig.ts
This PR adds option `--no-trailing-comma-php`.
If set to true, no trailing commas are printed for php expression.',
- https://github.com/shufo/prettier-plugin-blade/issues/231
PHP version below 7.2 can't recognize trailing comma on php expression. So we should support `trailingCommaPHP` option in `@prettier/plugin-php` for backward compatibility.
see tests
> feat: 🎸 add option `--no-trailing-comma-php`

- __tests__/fixtures/formatted.raw_php_block.blade.php
- __tests__/fixtures/snapshots/php_block_directive.snapshot
- src/formatter.ts
This PR fixes https://github.com/shufo/prettier-plugin-blade/issues/239
- https://github.com/shufo/prettier-plugin-blade/issues/239
There is an unnecessary indent spaces on blank line in `@php` ~ `@endphp` directive
see tests
> fix: 🐛 unnecessary indent in raw php directive

- __tests__/formatter.test.ts
- src/formatter.ts
This PR fixes https://github.com/shufo/prettier-plugin-blade/issues/235
- https://github.com/shufo/prettier-plugin-blade/issues/235
Long props are not formatted correctly.
see tests
> fix: 🐛 long props collapse into single line

- __tests__/fixtures/snapshots/livewire_params.snapshot
- src/formatter.ts
This PR fixes https://github.com/shufo/vscode-blade-formatter/issues/813
- https://github.com/shufo/vscode-blade-formatter/issues/813
Livewire params should not be formatted by this formatter
see tests
> fix: 🐛 livewire params is formatted unexpectedly

- __tests__/formatter.test.ts
- src/formatter.ts
- src/util.ts
This updates the formatting logic so that "multiline, multi-statement" blocks (eg `@php`) blocks are formatted while respecting the configured `printWidth` or `wrap-line-length` parameter. I also try to dynamically adjust the printWidth based on the current indent level, so that more-deeply indented lines are formatted onto shorter and shorter lines ... just as the `@prettier/plugin-php` would do for more deeply nested lines.
This should close #908 and, I think, should also allow https://github.com/shufo/prettier-plugin-blade/issues/266 to be closed.
I mostly consume this project via the prettier plugin, and I usually want the formatting of PHP in Blade files to match what it would look like in regular PHP files, which I also format with prettier. The current behavior of "wrapping" nearly …
> feat: improve formatting of @php blocks (close #908)

- __tests__/formatter.test.ts
- src/formatter.ts
When implementing #909, I misunderstood what `indent.amount` represents. I thought it was the number of indent levels, but it's actually the number of indent characters. This corrects that behavior and should improve the formatting of deeply (and not-so-deeply) indented `@php` blocks.
Fixes #914 and #915
See #915
I added a test, and ran it on several templates.
With this change, the code from #915 is formatted as expected: both PHP blocks are formatted identically.
```
@php
if (1) {
if (1) {
if (1) {
if (1) {
if (1) {
if (1) {
$percent =
$item['historical'] ?? null
? round(
(100 *
($item['today'] -
$item['historical'])) /
$item['historical'],
)
: null;
$color = $percent < 0 ? '#8b0000' : '#006400';
}
}
}
}
}
}
@endphp
<div>
<div>
<div>
<div>
<div>
<div>
@php
$percent =
$item['historical'] …
```
> fix(formatter): correct indent level for raw @php blocks (close #915, #914)

- README.md
- __tests__/cli.test.ts
- __tests__/fixtures/argumentTest/componentPrefix/formatted.index.blade.php
- __tests__/fixtures/argumentTest/componentPrefix/index.blade.php
- __tests__/formatter.test.ts
- src/cli.ts
- src/formatter.ts
- src/main.ts
- src/runtimeConfig.ts
Add a new option `componentPrefix` for html attr format.
closes #942 closes #944 
Due to currently only prefix of `x-` or `livewire:` treat as custom component and format html attr differently, thus for new libs like `flux` which uses prefix of `flux:`. The result of the format will cause a syntex error. e.g. `:key="$foo - > bar"`
Both cli and formatter test cases added.
> feat: add option `--component-prefix`

- package.json
- src/main.ts
- yarn.lock
This PR bumps node-glob to v10 because node-glob v8 is deprecated
- closes: #945
test passed
> chore(deps): bump glob to v10

- __tests__/formatter/builtin-directives.test.ts
- src/formatter.ts
- refs: #941
This PR fixes indenting problem that `@break` directive inside `@if` directive gets unexpected indenting.
e.g.
```blade
@if ($user)
@break
@endif
```
Current behaviour after formatting.
```blade
@if ($user)
@break
@endif
```
- fixes: #941
It should not be indented like laravel's official blade description for `@break` directive.
```blade
@foreach ($users as $user)
@if ($condition)
@break
@endif
@endforeach
```
passing tests.
> fix: 🐛 unexpected indent on break directive inside if directive

- __tests__/formatter/js.test.ts
- src/indent.ts
This PR fixes <https://github.com/shufo/prettier-plugin-blade/issues/305>
- <https://github.com/shufo/prettier-plugin-blade/issues/305>
`@js` directive introduced in laravel 8.x should be supported
passing the tests
> fix: 🐛 `@js` directive in script tag replaced as undefined

- __tests__/formatter/ignore.test.ts
- package.json
- src/processors/ignoredLinesProcessor.ts
- yarn.lock
When using [Jigsaw](https://github.com/tighten/jigsaw) from Tighten, we leverage YAML Front Matter from within [Blade files](https://github.com/tighten/jigsaw-blog-template/blob/main/source/blog.blade.php) in order to enrich template files. This block is always at the start of the file.
When using this formatter alongside the [Prettier plugin](https://github.com/shufo/prettier-plugin-blade), it will try to format Front Matter parts, and corrupt it.
```blade
---
title: Blog
description: The list of blog posts for the site
pagination:
collection: posts
perPage: 4
---
@extends('_layouts.main')
```
will become
```blade
---
title: Blog
description: The list of blog posts for the site
pagination:
collection: posts
perPage: 4
---
@extends('_layouts.main')
```
but the indentation is important …
> fix: ignore Front Matter blocks

- src/processors/shorthandBindingProcessor.ts
The recoveryShorthandBinding function has been updated to prevent automatic formatting of expressions containing the -> operator, commonly used in PHP.
> ### Template before formatting
> :param="auth()->user->name"
> ### Template after formatting
> :param="auth() - > user - > name"
> ### Expected Behaviour
> :param="auth()->user->name"
The formatter previously attempted to format expressions containing PHP syntax (->), which resulted in incorrect formatting or unexpected behavior. This change ensures that such expressions are preserved as-is and not passed through the JS beautifier.
> If it is a PHP expression (contains ->), it does not format it
